# Generated by Django 3.1.1 on 2020-09-08 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200908_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created',
            new_name='modified',
        ),
    ]
