# Generated by Django 3.1.1 on 2020-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(default='Junk', max_length=10),
        ),
    ]
