# Generated by Django 3.1.1 on 2020-09-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_note_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
